# Generated by Django 4.1.1 on 2022-09-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
